/*
 * Copyright 2020-2021 NXP
 *
 * SPDX-License-Identifier: BSD-3-Clause
 */

#ifndef __S32G_MC_RGM_H__
#define __S32G_MC_RGM_H__

#include "s32_mc_rgm.h"

#define MC_RGM_RDSS	(S32_MC_RGM_BASE_ADDR + 0x24)
#define RDSS_FES_RES	BIT(1)
#define RDSS_DES_RES	BIT(0)

enum reset_cause {
	CAUSE_POR,
	CAUSE_DESTRUCTIVE_RESET_DURING_RUN,
	CAUSE_DESTRUCTIVE_RESET_DURING_STANDBY,
	CAUSE_FUNCTIONAL_RESET_DURING_RUN,
	CAUSE_FUNCTIONAL_RESET_DURING_STANDBY,
	CAUSE_WAKEUP_DURING_STANDBY,
	CAUSE_ERROR
};

#endif /* __S32G_MC_RGM_H__ */
